org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

unity.applicationId=com.example.vibelab.unity1
unity.namespace=com.example.vibelab.unity1
unity.versionName=1.0.0
unity.versionCode=1
unity.compileSdkVersion=35
unity.targetSdkVersion=35
unity.minSdkVersion=23
unity.abiFilters=arm64-v8a
unity.debugSymbolLevel=none
unityTemplateVersion=25
unityProjectPath=
unity.projectPath=
